config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "home#index"
  # root to: "contents#index"
  resources :agreements
  resources :users_sports
  resources :sports
  resources :places
  resources :contents do
    collection do
      get :coach, to: "contents#coach_index"
    end
    member do
      get :coach, to: "contents#coach_show"
      delete :coach, to: "contents#coach_destroy"
    end
  end
  resources :users
  resource :self
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/content.rb
# == Schema Information
#
# Table name: contents
#
#  id             :integer          not null, primary key
#  place_id       :integer
#  user_id        :integer
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#  menu           :text
#  scheduled_date :date
#  scheduled_time :time
#

class Content < ApplicationRecord

  belongs_to :place
  belongs_to :user
  has_many :agreements

  validates :scheduled_time, presence: true
  validates :scheduled_date, presence: true
  validates :place_id, presence: true
  validates :scheduled_time, presence: true
end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController
  load_and_authorize_resource

  # GET /contents
  # GET /contents.json
  def index
    @contents = @contents.where('scheduled_date = ?', params[:date]) if params[:date]
    @contents = @contents.all

    @current_user = current_user

    @contents = @contents.page(params[:page])

    # for console
    p current_user
  end

  # coach index
  def coach_index
    @contents = @contents.where('scheduled_date = ?', params[:date]) if params[:date]
    @contents = @contents.all

    @agreements = current_user.agreements

    @contents = @contents.page(params[:page])

    # for console
    p current_user

  end

  # GET /contents/1
  # GET /contents/1.json
  def show

    p "---------"
    p @contents

  end

  # GET /contents/new
  def new
    @content = Content.new
  end

  # GET /contents/1/edit
  def edit; end

  # POST /contents
  # POST /contents.json
  def create
    @content = Content.new(content_params)
    @content.user_id = current_user.id
    p "--------------"
    p @content.errors
    p content_params

    respond_to do |format|
      if @content.save
        format.html { redirect_to coach_contents_url, notice: 'Content was successfully created.' }
        format.json { render :show, status: :created, location: @content }
      else
        format.html { render :new }
        format.json { render json: @content.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contents/1
  # PATCH/PUT /contents/1.json
  def update
    respond_to do |format|
      if @content.update(content_params)
        format.html { redirect_to coach_contents_url, notice: 'Content was successfully updated.' }
        format.json { render :show, status: :ok, location: @content }
      else
        format.html { render :edit }
        format.json { render json: @content.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contents/1
  # DELETE /contents/1.json
  def destroy
    @content.destroy
    respond_to do |format|
      format.html { redirect_to contents_url, notice: 'Content was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # DELETE /contents/1/coach
  # DELETE /contents/1/coach.json
  def coach_destroy
    @content.destroy
    respond_to do |format|
      format.html { redirect_to coach_contents_url, notice: 'Content was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_content
    @content = Content.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def content_params
    params.fetch(:content, {}).permit(
    :place_id, :scheduled_date, :scheduled_time, :menu,
    )
  end
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/views/contents/_coach_detail.html.erb
<!-- coacn_contents detail common parts -->

<table class="table">
  <h3 class="pb-2"><%= content.scheduled_date %></h3>
    <tbody>
      <tr>
        <th scope="row"></th>
        <td>【場所】</td>
        <td><%= content.place.name %></td>
      </tr>
      <tr>
        <th scope="row"></th>
        <td>【メニュー】</td>
        <td><%= content.menu %></td>
      </tr>
      <tr>
        <th scope="row"></th>
        <td>【生徒一覧】</td>
        <td><% content.agreements.each do |agreement| %>
          <p>
            <%= agreement.user.name || agreement.user.email  %>　<%= agreement.status %>
            <% if agreement.status == 'request' %>
                <%= link_to "承認する", agreement_url(agreement.id, params: {agreement: {status: :agree}}), method: :put %>
                / <%= link_to "拒否する", agreement_url(agreement.id, params: {agreement: {status: :deny}}), method: :put %>
            <% end %>
            <% if agreement.status == 'agree' || agreement.status == 'deny'%>
                <%= link_to "差し戻す", agreement_url(agreement.id, params: {agreement: {status: :request}}), method: :put %>
            <% end %>
           </p>
        <% end %></td>
      </tr>
    </tbody>
  </table>

app/views/contents/_detail.html.erb
<!-- contents detail common parts -->
<table class="table">
  <h3 class="pb-2"><%= content.scheduled_date %></h3>
    <tbody>
      <tr>
        <th scope="row"></th>
        <td>【場所】</td>
        <td><%= content.place.name %></td>
      </tr>
      <tr>
        <th scope="row"></th>
        <td>【コーチ】</td>
        <td><%= content.user.name %></td>
      </tr>
      <tr>
        <th scope="row"></th>
        <td>【メニュー】</td>
        <td><%= content.menu %></td>
      </tr>
    </tbody>
  </table>

app/views/contents/_form.html.erb
<div class="border pb-3">
<%= form_with(model: content, local: true) do |f| %>
  <% if content.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(content.errors.count, "error") %> prohibited this content from being saved:</h2>

      <ul>
      <% content.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <fieldset class="form-group row container" >
      <legend class="col-form-legend col-sm-2">場所</legend>
      <div class="col-sm-10">
        <% Place.all.each do |place| %>
        <div class="form-check">
          <label class="form-check-label">
            <%= f.radio_button :place_id, place.id, class: "form-check-input"%>
            <%= place.name %>
          </label>
        </div>
        <% end %>
      </div>
    </fieldset>
    <div class="form-group row container">
      <label for="inputEmail3" class="col-sm-2 col-form-label">日付</label>
      <div class="col-sm-10">
        <% date = content.scheduled_date || params[:date] || "" %>
        <%= f.text_field :scheduled_date, type: "date", class: "form-control", value: date, readonly: true %>
      </div>
    </div>
    <div class="form-group row container">
      <label for="inputEmail3" class="col-sm-2 col-form-label">時間</label>
      <div class="col-sm-10">

        <%= f.text_field :scheduled_time, type: "time", class: "form-control" %>
      </div>
    </div>

    <div class="form-group row container">
      <label for="inputEmail3" class="col-sm-2 col-form-label">メニュー</label>
      <div class="col-sm-10">

        <%= f.text_area :menu, class: "form-control" %>
      </div>
    </div>

  <div class="actions text-center">
    <%= f.submit :class=>"btn btn-primary" %>
  </div>
<% end %>
</div>

app/views/contents/coach_index.html.erb
<div class="container-fluid col">
  <div class="row">
    <div class="col-6">
      <div class="list-group">

        <% if @contents.length == 0 %>
        <div class="container-fluid">
          <div class="alert alert-light text-center my-3" role="alert">
            登録している練習は0件です
          </div>
        </div>
        <% end %>

        <% @contents.each do |content| %>

          <%= link_to coach_content_url(content), class: "list-group-item list-group-item-action flex-column align-items-start mb-3" do %>
          <table class="table">
            <h3 class="pb-2"><%= formated_date content.scheduled_date %></h3>
              <tbody>
                <tr>
                  <th scope="row"></th>
                  <td>【場所】</td>
                  <td><%= content.place.name %></td>
                </tr>
                <tr>
                  <th scope="row"></th>
                  <td>【生徒】</td>
                  <td><%= content.agreements.count %>人</td>
                </tr>
              </tbody>
            </table>
          <% end %>
        <% end %>
        <%= paginate @contents %>
      </div>
    </div>
    <div class="kalender col-6">
      <form method="get" action="<%= new_content_path %>">
        <p><input type="date" name="date" value="<%= params[:date] %>" required> <strong>必須</strong></p>
        <p><input type="submit" value="練習を登録する" class="btn btn-primary btn-sm"></p>
      </form>
      <%= image_tag("kalender.jpg", style: 'width:100%') %>
    </div>
  </div>
</div>

app/views/contents/coach_show.html.erb
<div class="container">
    <div class="my-3">
      <%= link_to '戻る', coach_contents_path, class: "btn btn-primary" %>
      <%= link_to '練習変更', edit_content_path(@content), class: "btn btn-primary" %>
      <%= link_to '練習削除', coach_content_path(@content), class: "btn btn-primary", method: :delete %>
    </div>
    <div class="container list-group-item">
      <%= render partial: "contents/coach_detail", locals: {content: @content, agreements: @content.agreements} %>
    </div>
</div>

app/views/contents/edit.html.erb
<div class="container">
  <div class="my-2">
    <%= link_to '戻る', coach_content_url, class: "btn btn-primary mb-2" %>
  </div>
  <%= render 'form', content: @content %>
</div>

app/views/contents/index.html.erb
<!-- <p id="notice"><%= notice %></p> -->


<div class="container-fluid col">
  <div class="row">
    <div class="col-6">
      <div class="list-group">

        <% if @contents.length == 0 %>
        <div class="container-fluid">
          <div class="alert alert-light text-center my-3" role="alert">
            登録されている練習は0件です
          </div>
        </div>
        <% end %>

        <% @contents.each do |content| %>
          <%= link_to content_url(content), class: "list-group-item list-group-item-action flex-column align-items-start mb-3" do %>
          <table class="table">
            <h3 class="pb-2"><%= formated_date content.scheduled_date %></h3>
              <tbody>
                <tr>
                  <th scope="row"></th>
                  <td>【場所】</td>
                  <td><%= content.place.name %></td>
                </tr>
                <tr>
                  <th scope="row"></th>
                  <td>【時間】</td>
                  <td><%= content.scheduled_time.strftime('%H時%M分') %></td>
                </tr>
                <tr>
                  <th scope="row"></th>
                  <td>【コーチ】</td>
                  <td><%= content.user.name || content.user.email %> / <%= content.user.gender %></td>
                </tr>
              </tbody>
            </table>
          <% end %>
        <% end %>
          <%= paginate @contents %>
      </div>
    </div>
    <div class="kalender col-6">
      <form method="get" action="<%= contents_path %>">
        <p><input type="date" name="date" value="<%= params[:date] %>" required> <strong>必須</strong></p>
        <p><input type="submit" value="コーチを探す" class="btn btn-primary btn-sm"></p>
      </form>
      <%= image_tag("kalender.jpg", style: 'width:100%') %>
    </div>
  </div>
</div>

app/views/contents/new.html.erb
<div class="container">
  <div class="my-2">
    <%= link_to '戻る', contents_path, class: "btn btn-primary mb-2" %>
  </div>
  <%= render 'form', content: @content %>
</div>

app/views/contents/show.html.erb
<div class="container">
  <div class="my-3">
    <%= link_to '戻る', contents_url, class: "btn btn-primary" %>
  </div>
  <div class="container list-group-item flex">
    <div class="container">
      <%= render partial: "contents/detail", locals: {content: @content} %>
    </div>
    <div class="text-center" id="container">
      <%= button_to "申請する", {controller: 'agreements', action: 'create', params: {agreement: {content_id: @content.id}} }, {class: "btn btn-primary"} %>
    </div>
  </div>
</div>