config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "home#index"
  # root to: "contents#index"
  resources :agreements
  resources :users_sports
  resources :sports
  resources :places
  resources :contents do
    collection do
      get :coach, to: "contents#coach_index"
    end
    member do
      get :coach, to: "contents#coach_show"
      delete :coach, to: "contents#coach_destroy"
    end
  end
  resources :users
  resource :self
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/sport.rb
# == Schema Information
#
# Table name: sports
#
#  id         :integer          not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Sport < ApplicationRecord
  has_many :users_sports
  has_many :users, through: :users_sports
end

app/controllers/sports_controller.rb
class SportsController < ApplicationController
  before_action :set_sport, only: %i[show edit update destroy]

  # GET /sports
  # GET /sports.json
  def index
    @sports = Sport.all
  end

  # GET /sports/1
  # GET /sports/1.json
  def show; end

  # GET /sports/new
  def new
    @sport = Sport.new
  end

  # GET /sports/1/edit
  def edit; end

  # POST /sports
  # POST /sports.json
  def create
    @sport = Sport.new(sport_params)

    respond_to do |format|
      if @sport.save
        format.html { redirect_to @sport, notice: 'Sport was successfully created.' }
        format.json { render :show, status: :created, location: @sport }
      else
        format.html { render :new }
        format.json { render json: @sport.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sports/1
  # PATCH/PUT /sports/1.json
  def update
    respond_to do |format|
      if @sport.update(sport_params)
        format.html { redirect_to @sport, notice: 'Sport was successfully updated.' }
        format.json { render :show, status: :ok, location: @sport }
      else
        format.html { render :edit }
        format.json { render json: @sport.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sports/1
  # DELETE /sports/1.json
  def destroy
    @sport.destroy
    respond_to do |format|
      format.html { redirect_to sports_url, notice: 'Sport was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_sport
    @sport = Sport.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def sport_params
    params.fetch(:sport, {})
  end
end

app/helpers/sports_helper.rb
module SportsHelper
end

app/views/sports/_form.html.erb
<%= form_with(model: sport, local: true) do |form| %>
  <% if sport.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(sport.errors.count, "error") %> prohibited this sport from being saved:</h2>

      <ul>
      <% sport.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/sports/edit.html.erb
<h1>Editing Sport</h1>

<%= render 'form', sport: @sport %>

<%= link_to 'Show', @sport %> |
<%= link_to 'Back', sports_path %>

app/views/sports/index.html.erb
<h1>Sports</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sports.each do |sport| %>
      <tr>
        <td><%= link_to 'Show', sport %></td>
        <td><%= link_to 'Edit', edit_sport_path(sport) %></td>
        <td><%= link_to 'Destroy', sport, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sport', new_sport_path %>

app/views/sports/new.html.erb
<h1>New Sport</h1>

<%= render 'form', sport: @sport %>

<%= link_to 'Back', sports_path %>

app/views/sports/show.html.erb
<!-- <p id="notice"><%= notice %></p> -->

<%= link_to 'Edit', edit_sport_path(@sport) %> |
<%= link_to 'Back', sports_path %>