config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "home#index"
  # root to: "contents#index"
  resources :agreements
  resources :users_sports
  resources :sports
  resources :places
  resources :contents do
    collection do
      get :coach, to: "contents#coach_index"
    end
    member do
      get :coach, to: "contents#coach_show"
      delete :coach, to: "contents#coach_destroy"
    end
  end
  resources :users
  resource :self
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/users_sport.rb
# == Schema Information
#
# Table name: users_sports
#
#  id         :integer          not null, primary key
#  user_id    :integer
#  sport_id   :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class UsersSport < ApplicationRecord
  belongs_to :user
  belongs_to :sport
end

app/controllers/users_sports_controller.rb
class UsersSportsController < ApplicationController
  before_action :set_users_sport, only: %i[show edit update destroy]

  # GET /users_sports
  # GET /users_sports.json
  def index
    @users_sports = UsersSport.all
  end

  # GET /users_sports/1
  # GET /users_sports/1.json
  def show; end

  # GET /users_sports/new
  def new
    @users_sport = UsersSport.new
  end

  # GET /users_sports/1/edit
  def edit; end

  # POST /users_sports
  # POST /users_sports.json
  def create
    @users_sport = UsersSport.new(users_sport_params)

    respond_to do |format|
      if @users_sport.save
        format.html { redirect_to @users_sport, notice: 'Users sport was successfully created.' }
        format.json { render :show, status: :created, location: @users_sport }
      else
        format.html { render :new }
        format.json { render json: @users_sport.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users_sports/1
  # PATCH/PUT /users_sports/1.json
  def update
    respond_to do |format|
      if @users_sport.update(users_sport_params)
        format.html { redirect_to @users_sport, notice: 'Users sport was successfully updated.' }
        format.json { render :show, status: :ok, location: @users_sport }
      else
        format.html { render :edit }
        format.json { render json: @users_sport.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users_sports/1
  # DELETE /users_sports/1.json
  def destroy
    @users_sport.destroy
    respond_to do |format|
      format.html { redirect_to users_sports_url, notice: 'Users sport was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_users_sport
    @users_sport = UsersSport.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def users_sport_params
    params.fetch(:users_sport, {})
  end
end

app/helpers/users_sports_helper.rb
module UsersSportsHelper
end

app/views/users_sports/_form.html.erb
<%= form_with(model: users_sport, local: true) do |form| %>
  <% if users_sport.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(users_sport.errors.count, "error") %> prohibited this users_sport from being saved:</h2>

      <ul>
      <% users_sport.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users_sports/edit.html.erb
<h1>Editing Users Sport</h1>

<%= render 'form', users_sport: @users_sport %>

<%= link_to 'Show', @users_sport %> |
<%= link_to 'Back', users_sports_path %>

app/views/users_sports/index.html.erb
<h1>Users Sports</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users_sports.each do |users_sport| %>
      <tr>
        <td><%= link_to 'Show', users_sport %></td>
        <td><%= link_to 'Edit', edit_users_sport_path(users_sport) %></td>
        <td><%= link_to 'Destroy', users_sport, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Users Sport', new_users_sport_path %>

app/views/users_sports/new.html.erb
<h1>New Users Sport</h1>

<%= render 'form', users_sport: @users_sport %>

<%= link_to 'Back', users_sports_path %>

app/views/users_sports/show.html.erb
<!-- <p id="notice"><%= notice %></p> -->

<%= link_to 'Edit', edit_users_sport_path(@users_sport) %> |
<%= link_to 'Back', users_sports_path %>